spring:
  profiles:
  - default
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/ubicare
    username: root
    password: ubimicro
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9077
---
spring:
  profiles:
  - dev
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.104:3306/ubicare
    username: root
    password: ubimicro
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9077
---
spring:
  profiles:
  - prod
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/ubicare
    username: root
    password: ubimicro
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9077

